image: lapi/gitlab-docker-sbt

services:
  - docker:dind

stages:
  - publishServer
  - publishClientLambda
  - publishClientStatic

publishServer:
  stage: publishServer
  script:
    - cd server/
    - docker login -u lapi -p $DOCKER_HUB_PASS
    - sbt clean dockerBuildAndPush

publishClientLambda:
  stage: publishClientLambda
  script:
    - >
      if git diff HEAD~ --name-only|grep server; then
        cd client-lambda/
        echo "Changes in lambda"
      fi;


publishClientStatic:
  stage: publishClientStatic
  script:
    - >
      if git diff HEAD~ --name-only|grep server; then
        cd client-static/
        echo "Changes in static"
      fi;
