image: hseeberger/scala-sbt:latest

services:
  - docker:dind

stages:
  - publish

before_script:
  # Log  the sbt version
  - sbt sbt-version
  - cd server/

publish:
  stage: publish
  script:
    - sbt clean dockerBuildAndPush
