image: strobe/gitlab-dind-sbt:latest

services:
  - docker:dind

stages:
  - publish

before_script:
  # Log  the sbt version
  - sbt sbt-version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - cd server/

publish:
  stage: publish
  script:
    - sbt clean dockerBuildAndPush
