image: lapi/test-docker-java:latest

services:
  - docker:dind

stages:
  - publish

before_script:
  # Log  the sbt version
  - sbt sbt-version
  - cd server/

publish:
  stage: publish
  script:
    - docker login -u lapi -p $DOCKER_HUB_PASS
    - sbt clean dockerBuildAndPush
