image: lapi/sbt-with-docker:latest

stages:
  - test
  - publish

before_script:
  # Log the sbt version
  - sbt sbt-version
  - cd server/

test:
  stage: test
  script:
    # Execute your project's tests
    - sbt clean test

publish:
  stage: publish
  script:
    - sbt dockerBuildAndPush
