image: strobe/gitlab-dind-sbt:latest

services:
  - docker:dind

stages:
  - publish

before_script:
  # Log  the sbt version
  - sbt sbt-version
  - echo $TEST
  - docker login -u lapi -p $DOCKER_HUB_PASS hub.docker.com
  - cd server/

publish:
  stage: publish
  script:
    - sbt clean dockerBuildAndPush
